import ReactMarkdown from "react-markdown";
import { FileText, Download, Clock, Hash } from "lucide-react";

export default function BriefPanel({ brief, query }) {
  if (!brief) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-3"
        style={{ color: "var(--text-3)" }}>
        <FileText className="w-10 h-10 opacity-30" />
        <p className="text-sm">The executive brief will appear here when complete</p>
      </div>
    );
  }

  const words    = brief.trim().split(/\s+/).length;
  const readMins = Math.max(1, Math.ceil(words / 200));

  const handleDownload = () => {
    const blob = new Blob([brief], { type: "text/markdown" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    const slug = (query || "brief").toLowerCase().replace(/\s+/g, "-").slice(0, 40);
    a.href     = url;
    a.download = `market-research-${slug}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="anim-fade-in">
      {/* Action bar */}
      <div className="glass-card px-5 py-3.5 mb-4 flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-1.5 text-xs" style={{ color: "var(--text-3)" }}>
            <Hash className="w-3.5 h-3.5" />
            <span className="mono">{words.toLocaleString()}</span> words
          </div>
          <div className="w-px h-4" style={{ background: "var(--border)" }} />
          <div className="flex items-center gap-1.5 text-xs" style={{ color: "var(--text-3)" }}>
            <Clock className="w-3.5 h-3.5" />
            {readMins} min read
          </div>
          <div className="w-px h-4" style={{ background: "var(--border)" }} />
          <span className="tag"
            style={{ background: "rgba(16,185,129,0.1)", color: "#34d399", borderColor: "rgba(16,185,129,0.25)" }}>
            Ready
          </span>
        </div>

        <button onClick={handleDownload}
          className="flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-xl transition-all duration-200 cursor-pointer"
          style={{ background: "rgba(99,102,241,0.1)", color: "#a5b4fc", border: "1px solid rgba(99,102,241,0.25)" }}
          onMouseEnter={e => { e.currentTarget.style.background = "rgba(99,102,241,0.18)"; e.currentTarget.style.borderColor = "rgba(99,102,241,0.45)"; }}
          onMouseLeave={e => { e.currentTarget.style.background = "rgba(99,102,241,0.1)";  e.currentTarget.style.borderColor = "rgba(99,102,241,0.25)"; }}>
          <Download className="w-4 h-4" />
          Download .md
        </button>
      </div>

      {/* Brief body */}
      <div className="glass-card overflow-hidden">
        {/* Gradient header stripe */}
        <div className="h-1 w-full"
          style={{ background: "linear-gradient(90deg, #6366f1, #8b5cf6, #a78bfa)" }} />

        <div className="p-8 lg:p-12">
          <div className="prose-brief max-w-none">
            <ReactMarkdown>{brief}</ReactMarkdown>
          </div>
        </div>

        {/* Footer */}
        <div className="px-8 lg:px-12 pb-6">
          <div className="pt-6 flex items-center justify-between flex-wrap gap-3"
            style={{ borderTop: "1px solid var(--border)" }}>
            <p className="text-xs" style={{ color: "var(--text-3)" }}>
              Generated by Llama 3.3 70B · Market Research Assistant
            </p>
            <button onClick={handleDownload}
              className="flex items-center gap-1.5 text-xs cursor-pointer transition-colors duration-150"
              style={{ color: "var(--text-3)" }}
              onMouseEnter={e => { e.currentTarget.style.color = "#818cf8"; }}
              onMouseLeave={e => { e.currentTarget.style.color = "var(--text-3)"; }}>
              <Download className="w-3 h-3" />
              Save as Markdown
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
